[003.2] Finished code for the computer's turn | H.C.
SpaTeamAcademy/Team_A pull request #3
Opened 2023-07-21 08:49 UTC by iobosse03

003.2 Schere Stein Papier https://app.asana.com/0/1205072348884926/1205082265132033/f

Contains code for 003.3 that is commented out

2023-07-21 09:08 UTC, SpaTeamAcademy requested changes
Clean Coding || Leserlichkeit des Codes

-> Klicken des Buttons könnte auch gleich "Rock", "Paper" oder "Scissor" als Parameter übergeben, damit muss nicht zwischen Zahlen und Text konvertiert werden

-> Warum wird zwischen "Rock" und "rock" unterschieden? Das verdoppelt lediglich den Code in der function toText() || DRY-Prinzip

-> sollte Groß-/Kleinschreibung zwingend notwendig sein, seht euch die entspechenden string-Methoden dazu an (.toUpperCase(), .toLowerCase())

2023-07-21 10:04 UTC, iobosse03 commented
Sollen alle Funktionen, die die Zahlen verwenden auf Strings geändert werden, oder nur die toText() Funktion?

2023-07-21 10:09 UTC, SpaTeamAcademy commented
Für die Leserlichkeit würde ich empfehlen Strings statt Zahlen zu verwenden. Ihr spart euch dadurch einerseits erklärende Kommentare, welche Zahlen wofür stehen. Weiters könnt ihr mit strings leichter und verständlicher arbeiten, wenn der Code z.B. nachträglich geändert werden muss (Ihr müsst euch dann auch nicht selbst immer wieder überlegen, wofür zB. die 1 steht)

Im weiteren Verlauf führt das zu weniger Verwirrung bei den Logikoperationen ("rock" == "rock") und Gewinnbedingungen (0 = Rock und 0 = Draw).

2023-07-24 07:37 UTC, iobosse03 commented
Code review: J.H.

2023-07-24 08:19 UTC, SpaTeamAcademy approved these changes

2023-07-24 08:19 UTC, merged